[package]
name = "actix-jwt"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
jsonwebtoken = "9.3.0"
rusqlite = { version = "0.32.1", features = ["bundled"] }
serde = { version = "1.0.209", features = ["derive"]}
chrono = "0.4.38"